2025-02-20 21:17:52.592 | INFO     | __main__:__init__:28 - Starting up...
2025-02-20 21:18:13.247 | INFO     | __main__:__init__:28 - Starting up...
2025-02-20 21:18:13.247 | INFO     | __main__:create_app:53 - Creating Server...
2025-02-20 21:18:34.652 | INFO     | __main__:__log:47 - 127.0.0.1 /
2025-02-20 21:19:02.238 | INFO     | __main__:__init__:28 - Starting up...
2025-02-20 21:19:02.239 | INFO     | __main__:create_app:53 - Creating Server...
2025-02-20 21:19:07.109 | INFO     | __main__:__log:47 - 127.0.0.1 /
2025-02-21 15:43:15.136 | INFO     | __main__:__init__:28 - Starting up...
2025-02-21 15:43:15.138 | INFO     | __main__:create_app:53 - Creating Server...
2025-02-21 15:43:20.111 | INFO     | __main__:__log:47 - 127.0.0.1 /
2025-02-22 18:04:48.197 | INFO     | __main__:__init__:31 - Starting up...
2025-02-22 18:04:48.199 | INFO     | __main__:create_app:59 - Creating Server...
2025-02-22 18:04:53.979 | INFO     | __main__:__log:53 - 127.0.0.1 /
2025-02-22 18:05:47.349 | INFO     | __main__:__init__:31 - Starting up...
2025-02-22 18:05:47.355 | INFO     | __main__:create_app:59 - Creating Server...
2025-02-22 18:05:51.466 | INFO     | __main__:__log:53 - 127.0.0.1 /
2025-02-22 18:06:36.737 | INFO     | __main__:__init__:31 - Starting up...
2025-02-22 18:06:36.744 | INFO     | __main__:create_app:59 - Creating Server...
2025-02-22 18:06:39.811 | INFO     | __main__:__log:53 - 127.0.0.1 /
2025-02-22 18:07:11.176 | INFO     | __main__:__init__:31 - Starting up...
2025-02-22 18:07:11.176 | INFO     | __main__:create_app:59 - Creating Server...
2025-02-22 18:07:13.887 | INFO     | __main__:__log:53 - 127.0.0.1 /
2025-02-22 18:17:42.742 | INFO     | __main__:__init__:31 - Starting up...
2025-02-22 18:17:42.743 | INFO     | __main__:create_app:59 - Creating Server...
2025-02-22 18:17:48.029 | INFO     | __main__:__log:53 - 127.0.0.1 /
2025-02-22 18:17:54.256 | INFO     | __main__:__init__:31 - Starting up...
2025-02-22 18:17:54.262 | INFO     | __main__:create_app:59 - Creating Server...
2025-02-22 18:18:22.055 | INFO     | __main__:__log:53 - 127.0.0.1 /
2025-02-22 18:21:57.991 | INFO     | __main__:__init__:31 - Starting up...
2025-02-22 18:21:57.992 | INFO     | __main__:create_app:59 - Creating Server...
2025-02-22 18:22:00.893 | INFO     | __main__:__log:53 - 127.0.0.1 /
2025-02-22 18:36:53.828 | INFO     | __main__:__init__:31 - Starting up...
2025-02-22 18:36:53.829 | INFO     | __main__:create_app:59 - Creating Server...
2025-02-22 18:36:58.323 | INFO     | __main__:__log:53 - 127.0.0.1 /
2025-02-22 19:19:48.316 | INFO     | __main__:__init__:34 - Starting up...
2025-02-22 19:19:48.322 | INFO     | __main__:create_app:63 - Creating Server...
2025-02-22 19:19:52.143 | INFO     | __main__:__log:57 - 127.0.0.1 /
2025-02-22 19:20:27.600 | INFO     | __main__:__init__:34 - Starting up...
2025-02-22 19:20:27.606 | INFO     | __main__:create_app:63 - Creating Server...
2025-02-22 19:20:30.633 | INFO     | __main__:__log:57 - 127.0.0.1 /
2025-02-22 19:20:52.389 | INFO     | __main__:__init__:34 - Starting up...
2025-02-22 19:20:52.395 | INFO     | __main__:create_app:63 - Creating Server...
2025-02-22 19:20:54.583 | INFO     | __main__:__log:57 - 127.0.0.1 /
2025-02-22 19:23:01.489 | INFO     | __main__:__init__:34 - Starting up...
2025-02-22 19:23:01.490 | INFO     | __main__:create_app:63 - Creating Server...
2025-02-22 19:23:04.867 | INFO     | __main__:__log:57 - 127.0.0.1 /
2025-02-22 19:23:20.162 | INFO     | __main__:__init__:34 - Starting up...
2025-02-22 19:23:20.168 | INFO     | __main__:create_app:63 - Creating Server...
2025-02-22 19:23:22.566 | INFO     | __main__:__log:57 - 127.0.0.1 /
2025-02-22 19:25:24.973 | INFO     | __main__:__init__:34 - Starting up...
2025-02-22 19:25:24.980 | INFO     | __main__:create_app:63 - Creating Server...
2025-02-22 19:25:36.126 | INFO     | __main__:__log:57 - 127.0.0.1 /
2025-02-22 19:26:26.827 | INFO     | __main__:__init__:34 - Starting up...
2025-02-22 19:26:26.828 | INFO     | __main__:create_app:63 - Creating Server...
2025-02-22 19:26:26.853 | INFO     | __main__:__log:57 - 127.0.0.1 /
2025-02-25 16:00:58.838 | INFO     | __main__:__init__:34 - Starting up...
2025-02-25 16:00:58.839 | INFO     | __main__:create_app:63 - Creating Server...
2025-02-25 16:01:05.625 | INFO     | __main__:__log:57 - 127.0.0.1 /
2025-02-25 16:03:35.630 | INFO     | __main__:__init__:34 - Starting up...
2025-02-25 16:03:35.636 | INFO     | __main__:create_app:63 - Creating Server...
2025-02-25 16:03:37.507 | INFO     | __main__:__log:57 - 127.0.0.1 /
2025-02-25 16:04:30.487 | INFO     | __main__:__init__:34 - Starting up...
2025-02-25 16:04:30.488 | INFO     | __main__:create_app:63 - Creating Server...
2025-02-25 16:04:30.623 | INFO     | __main__:__log:57 - 127.0.0.1 /
2025-02-25 16:04:35.808 | INFO     | __main__:__log:57 - 127.0.0.1 /
2025-02-25 16:05:46.532 | INFO     | __main__:__init__:34 - Starting up...
2025-02-25 16:05:46.538 | INFO     | __main__:create_app:63 - Creating Server...
2025-02-25 16:05:49.492 | INFO     | __main__:__log:57 - 127.0.0.1 /
2025-02-25 16:08:04.835 | INFO     | __main__:__init__:34 - Starting up...
2025-02-25 16:08:04.836 | INFO     | __main__:create_app:63 - Creating Server...
2025-02-25 16:08:07.680 | INFO     | __main__:__log:57 - 127.0.0.1 /
2025-02-25 16:08:44.698 | INFO     | __main__:__init__:34 - Starting up...
2025-02-25 16:08:44.699 | INFO     | __main__:create_app:63 - Creating Server...
2025-02-25 16:08:48.555 | INFO     | __main__:__log:57 - 127.0.0.1 /
2025-02-25 16:09:22.346 | INFO     | __main__:__init__:34 - Starting up...
2025-02-25 16:09:22.347 | INFO     | __main__:create_app:63 - Creating Server...
2025-02-25 16:09:25.087 | INFO     | __main__:__log:57 - 127.0.0.1 /
2025-02-25 16:09:30.552 | INFO     | __main__:__init__:34 - Starting up...
2025-02-25 16:09:30.557 | INFO     | __main__:create_app:63 - Creating Server...
2025-02-25 16:10:38.479 | INFO     | __main__:__log:57 - 127.0.0.1 /
2025-02-25 16:16:11.105 | INFO     | __main__:__init__:34 - Starting up...
2025-02-25 16:16:11.107 | INFO     | __main__:create_app:63 - Creating Server...
2025-02-25 16:16:14.005 | INFO     | __main__:__log:57 - 127.0.0.1 /
2025-02-25 16:26:06.558 | INFO     | __main__:__init__:34 - Starting up...
2025-02-25 16:26:06.558 | INFO     | __main__:create_app:63 - Creating Server...
2025-02-25 16:26:09.102 | INFO     | __main__:__log:57 - 127.0.0.1 /
2025-02-25 17:08:57.850 | INFO     | __main__:__init__:34 - Starting up...
2025-02-25 17:08:57.851 | INFO     | __main__:create_app:63 - Creating Server...
2025-02-25 17:09:01.155 | INFO     | __main__:__log:57 - 127.0.0.1 /
2025-02-26 21:28:42.464 | INFO     | __main__:__init__:36 - Starting up...
2025-02-26 21:28:42.525 | ERROR    | __main__:<module>:87 - An error has been caught in function '<module>', process 'MainProcess' (15060), thread 'MainThread' (17600):
Traceback (most recent call last):

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\connection_cext.py", line 365, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
    │    │       │         └ {'host': 'localhost', 'user': '', 'password': 'local_master_project', 'password1': '', 'password2': '', 'password3': '', 'dat...
    │    │       └ <method 'connect' of '_mysql_connector.MySQL' objects>
    │    └ <_mysql_connector.MySQL object at 0x000001AE940E2E70>
    └ <mysql.connector.connection_cext.CMySQLConnection object at 0x000001AE93C83FB0>

_mysql_connector.MySQLInterfaceError: Access denied for user 'ODBC'@'localhost' (using password: YES)


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

> File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 87, in <module>
    fa = FlaskApp()
         └ <class '__main__.FlaskApp'>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 48, in __init__
    self.db = Database(host=args['dbhost'], user=args['dbuser'], password=args['dbpw'], database=args['dbschema'],
    │         │             │                    │                        │                      └ {'dbhost': 'localhost', 'dbschema': 'root', 'dbuser': '', 'dbpw': 'local_master_project'}
    │         │             │                    │                        └ {'dbhost': 'localhost', 'dbschema': 'root', 'dbuser': '', 'dbpw': 'local_master_project'}
    │         │             │                    └ {'dbhost': 'localhost', 'dbschema': 'root', 'dbuser': '', 'dbpw': 'local_master_project'}
    │         │             └ {'dbhost': 'localhost', 'dbschema': 'root', 'dbuser': '', 'dbpw': 'local_master_project'}
    │         └ <class 'backend.db.Database.Database'>
    └ <__main__.FlaskApp object at 0x000001AE93F797F0>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\backend\db\Database.py", line 26, in __init__
    self.pool = self.create_pool(pool_name=pool_name, pool_size=pool_size)
    │           │    │                     │                    └ 15
    │           │    │                     └ 'mypool'
    │           │    └ <function Database.create_pool at 0x000001AE94B2BB00>
    │           └ <backend.db.Database.Database object at 0x000001AE94B278F0>
    └ <backend.db.Database.Database object at 0x000001AE94B278F0>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\backend\db\Database.py", line 37, in create_pool
    pool = mysql.connector.pooling.MySQLConnectionPool(
           │     │         │       └ <class 'mysql.connector.pooling.MySQLConnectionPool'>
           │     │         └ <module 'mysql.connector.pooling' from 'C:\\Users\\chris\\OneDrive\\Desktop\\Masterarbeit neu\\project\\.venv\\Lib\\site-pack...
           │     └ <module 'mysql.connector' from 'C:\\Users\\chris\\OneDrive\\Desktop\\Masterarbeit neu\\project\\.venv\\Lib\\site-packages\\my...
           └ <module 'mysql' from 'C:\\Users\\chris\\OneDrive\\Desktop\\Masterarbeit neu\\project\\.venv\\Lib\\site-packages\\mysql\\__ini...

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\pooling.py", line 490, in __init__
    self.add_connection()
    │    └ <function MySQLConnectionPool.add_connection at 0x000001AE939E5120>
    └ <mysql.connector.pooling.MySQLConnectionPool object at 0x000001AE94B27FE0>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\pooling.py", line 613, in add_connection
    cnx = connect(**self._cnx_config)  # type: ignore[assignment]
          │         │    └ {'host': 'localhost', 'port': '3306', 'user': '', 'password': 'local_master_project', 'database': 'root'}
          │         └ <mysql.connector.pooling.MySQLConnectionPool object at 0x000001AE94B27FE0>
          └ <function connect at 0x000001AE939E45E0>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
           │                 │       └ {'host': 'localhost', 'port': '3306', 'user': '', 'password': 'local_master_project', 'database': 'root'}
           │                 └ ()
           └ <class 'mysql.connector.connection_cext.CMySQLConnection'>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\connection_cext.py", line 153, in __init__
    self.connect(**kwargs)
    │    │         └ {'host': 'localhost', 'port': '3306', 'user': '', 'password': 'local_master_project', 'database': 'root'}
    │    └ <function MySQLConnectionAbstract.connect at 0x000001AE91DF2020>
    └ <mysql.connector.connection_cext.CMySQLConnection object at 0x000001AE93C83FB0>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\abstracts.py", line 1529, in connect
    self._open_connection()
    │    └ <function CMySQLConnection._open_connection at 0x000001AE9397AF20>
    └ <mysql.connector.connection_cext.CMySQLConnection object at 0x000001AE93C83FB0>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\connection_cext.py", line 370, in _open_connection
    raise get_mysql_exception(
          └ <function get_mysql_exception at 0x000001AE91875440>

mysql.connector.errors.ProgrammingError: 1045 (28000): Access denied for user 'ODBC'@'localhost' (using password: YES)
2025-02-26 21:28:42.534 | INFO     | __main__:create_app:65 - Creating Server...
2025-02-26 21:30:11.294 | INFO     | __main__:__init__:36 - Starting up...
2025-02-26 21:30:11.355 | INFO     | __main__:create_app:65 - Creating Server...
2025-02-26 21:58:57.389 | INFO     | __main__:__init__:37 - Starting up...
2025-02-26 21:58:57.515 | INFO     | __main__:create_app:65 - Creating Server...
2025-02-26 21:59:05.105 | INFO     | __main__:__log:60 - 127.0.0.1 /
2025-02-26 21:59:05.187 | INFO     | __main__:__log:60 - 127.0.0.1 /css/bootstrap.min.css
2025-02-26 21:59:25.698 | INFO     | __main__:__log:60 - 127.0.0.1 /
2025-02-26 21:59:26.002 | INFO     | __main__:__log:60 - 127.0.0.1 /css/bootstrap.min.css
2025-02-26 22:03:28.142 | INFO     | __main__:__init__:38 - Starting up...
2025-02-26 22:03:28.142 | INFO     | __main__:__init__:38 - Starting up...
2025-02-26 22:03:28.199 | INFO     | __main__:create_app:57 - Creating Server...
2025-02-26 22:03:28.199 | INFO     | __main__:create_app:57 - Creating Server...
2025-02-26 22:09:57.551 | INFO     | __main__:__init__:38 - Starting up...
2025-02-26 22:09:57.611 | INFO     | __main__:create_app:58 - Creating Server...
2025-02-26 22:10:56.449 | INFO     | __main__:__init__:38 - Starting up...
2025-02-26 22:10:56.519 | INFO     | __main__:create_app:58 - Creating Server...
2025-02-26 22:11:00.416 | INFO     | backend.util.Toolbox:logToDatabase:23 - 127.0.0.1 /
2025-02-26 22:11:28.665 | INFO     | __main__:__init__:38 - Starting up...
2025-02-26 22:11:28.724 | INFO     | __main__:create_app:58 - Creating Server...
2025-02-26 22:11:32.742 | INFO     | backend.util.Toolbox:logToDatabase:23 - 127.0.0.1 /
2025-02-26 22:11:32.805 | INFO     | backend.util.Toolbox:logToDatabase:23 - 127.0.0.1 /css/bootstrap.min.css
2025-02-28 15:17:04.826 | INFO     | __main__:__init__:39 - Starting up...
2025-02-28 15:17:04.922 | INFO     | __main__:create_app:59 - Creating Server...
2025-02-28 15:17:10.445 | INFO     | backend.util.Toolbox:logToDatabase:42 - 127.0.0.1 /
2025-02-28 15:17:10.504 | INFO     | backend.util.Toolbox:logToDatabase:42 - 127.0.0.1 /css/bootstrap.min.css
2025-02-28 16:06:11.152 | INFO     | __main__:__init__:40 - Starting up...
2025-02-28 16:06:11.153 | INFO     | __main__:create_app:67 - Creating Server...
2025-02-28 16:08:32.125 | INFO     | __main__:__init__:40 - Starting up...
2025-02-28 16:08:32.126 | INFO     | __main__:create_app:60 - Creating Server...
2025-02-28 16:08:36.542 | INFO     | backend.util.Toolbox:logToDatabase:42 - 127.0.0.1 /
2025-02-28 16:08:36.573 | INFO     | backend.util.Toolbox:logToDatabase:42 - 127.0.0.1 /css/bootstrap.min.css
2025-04-01 18:06:12.008 | INFO     | __main__:__init__:40 - Starting up...
2025-04-01 18:06:12.009 | INFO     | __main__:create_app:60 - Creating Server...
2025-04-01 18:06:16.145 | ERROR    | __main__:<module>:101 - An error has been caught in function '<module>', process 'MainProcess' (29712), thread 'MainThread' (33620):
Traceback (most recent call last):

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\connection_cext.py", line 365, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
    │    │       │         └ {'host': 'localhost', 'user': 'root', 'password': '', 'password1': '', 'password2': '', 'password3': '', 'database': 'local_m...
    │    │       └ <method 'connect' of '_mysql_connector.MySQL' objects>
    │    └ <_mysql_connector.MySQL object at 0x00000211FE181D80>
    └ <mysql.connector.connection_cext.CMySQLConnection object at 0x00000211FE4BD040>

_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'localhost:3306' (10061)


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

> File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 101, in <module>
    fa.create_app()
    │  └ <function FlaskApp.create_app at 0x00000211FF88D6C0>
    └ <__main__.FlaskApp object at 0x00000211FE727AA0>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 62, in create_app
    self.__setupDB(self.app)
    │              │    └ <Flask 'main'>
    │              └ <__main__.FlaskApp object at 0x00000211FE727AA0>
    └ <__main__.FlaskApp object at 0x00000211FE727AA0>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 55, in __setupDB
    self.db = Database(host=configDict['db_hostname'], user=configDict['db_username'], password=configDict['db_password'], database=configDict['db_schema'],
    │         │             │                               │                                   │                                   └ {'db_hostname': ' localhost', 'db_schema': ' local_master_project', 'db_username': ' root', 'db_password': '', 'main_language...
    │         │             │                               │                                   └ {'db_hostname': ' localhost', 'db_schema': ' local_master_project', 'db_username': ' root', 'db_password': '', 'main_language...
    │         │             │                               └ {'db_hostname': ' localhost', 'db_schema': ' local_master_project', 'db_username': ' root', 'db_password': '', 'main_language...
    │         │             └ {'db_hostname': ' localhost', 'db_schema': ' local_master_project', 'db_username': ' root', 'db_password': '', 'main_language...
    │         └ <class 'backend.db.Database.Database'>
    └ <__main__.FlaskApp object at 0x00000211FE727AA0>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\backend\db\Database.py", line 26, in __init__
    self.pool = self.create_pool(pool_name=pool_name, pool_size=pool_size)
    │           │    │                     │                    └ 15
    │           │    │                     └ 'mypool'
    │           │    └ <function Database.create_pool at 0x00000211FF38EFC0>
    │           └ <backend.db.Database.Database object at 0x00000211FF86FE30>
    └ <backend.db.Database.Database object at 0x00000211FF86FE30>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\backend\db\Database.py", line 37, in create_pool
    pool = mysql.connector.pooling.MySQLConnectionPool(
           │     │         │       └ <class 'mysql.connector.pooling.MySQLConnectionPool'>
           │     │         └ <module 'mysql.connector.pooling' from 'C:\\Users\\chris\\OneDrive\\Desktop\\Masterarbeit neu\\project\\.venv\\Lib\\site-pack...
           │     └ <module 'mysql.connector' from 'C:\\Users\\chris\\OneDrive\\Desktop\\Masterarbeit neu\\project\\.venv\\Lib\\site-packages\\my...
           └ <module 'mysql' from 'C:\\Users\\chris\\OneDrive\\Desktop\\Masterarbeit neu\\project\\.venv\\Lib\\site-packages\\mysql\\__ini...

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\pooling.py", line 490, in __init__
    self.add_connection()
    │    └ <function MySQLConnectionPool.add_connection at 0x00000211FF877A60>
    └ <mysql.connector.pooling.MySQLConnectionPool object at 0x00000211FF8A0860>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\pooling.py", line 613, in add_connection
    cnx = connect(**self._cnx_config)  # type: ignore[assignment]
          │         │    └ {'host': ' localhost', 'port': '3306', 'user': ' root', 'password': '', 'database': ' local_master_project'}
          │         └ <mysql.connector.pooling.MySQLConnectionPool object at 0x00000211FF8A0860>
          └ <function connect at 0x00000211FF875080>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
           │                 │       └ {'host': ' localhost', 'port': '3306', 'user': ' root', 'password': '', 'database': ' local_master_project'}
           │                 └ ()
           └ <class 'mysql.connector.connection_cext.CMySQLConnection'>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\connection_cext.py", line 153, in __init__
    self.connect(**kwargs)
    │    │         └ {'host': ' localhost', 'port': '3306', 'user': ' root', 'password': '', 'database': ' local_master_project'}
    │    └ <function MySQLConnectionAbstract.connect at 0x00000211FF494F40>
    └ <mysql.connector.connection_cext.CMySQLConnection object at 0x00000211FE4BD040>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\abstracts.py", line 1529, in connect
    self._open_connection()
    │    └ <function CMySQLConnection._open_connection at 0x00000211FF851B20>
    └ <mysql.connector.connection_cext.CMySQLConnection object at 0x00000211FE4BD040>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\connection_cext.py", line 370, in _open_connection
    raise get_mysql_exception(
          └ <function get_mysql_exception at 0x00000211FF3E3600>

mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)
2025-04-01 18:17:26.501 | INFO     | __main__:__init__:40 - Starting up...
2025-04-01 18:17:26.501 | INFO     | __main__:create_app:60 - Creating Server...
2025-04-01 18:17:26.502 | ERROR    | __main__:<module>:86 - An error has been caught in function '<module>', process 'MainProcess' (20440), thread 'MainThread' (39248):
Traceback (most recent call last):

> File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 86, in <module>
    fa.create_app()
    │  └ <function FlaskApp.create_app at 0x000001E74B6E9800>
    └ <__main__.FlaskApp object at 0x000001E74B6CE750>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 62, in create_app
    self.__setupDB(self.app)
    │              │    └ <Flask 'main'>
    │              └ <__main__.FlaskApp object at 0x000001E74B6CE750>
    └ <__main__.FlaskApp object at 0x000001E74B6CE750>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 55, in __setupDB
    self.db = Database(host=configDict['db_hostname'], user=configDict['db_username'], password=configDict['db_password'], database=configDict['db_schema'],
    │         │             │                               │                                   │                                   └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         │             │                               │                                   └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         │             │                               └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         │             └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         └ <class 'backend.db.Database.Database'>
    └ <__main__.FlaskApp object at 0x000001E74B6CE750>

KeyError: 'db_hostname'
2025-04-01 18:17:45.967 | INFO     | __main__:__init__:40 - Starting up...
2025-04-01 18:18:13.153 | INFO     | __main__:__init__:40 - Starting up...
2025-04-01 18:18:13.153 | INFO     | __main__:create_app:60 - Creating Server...
2025-04-01 18:18:13.155 | ERROR    | __main__:<module>:86 - An error has been caught in function '<module>', process 'MainProcess' (38132), thread 'MainThread' (19892):
Traceback (most recent call last):

> File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 86, in <module>
    fa.create_app()
    │  └ <function FlaskApp.create_app at 0x000001E438309800>
    └ <__main__.FlaskApp object at 0x000001E4382EFD40>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 62, in create_app
    self.__setupDB(self.app)
    │              │    └ <Flask 'main'>
    │              └ <__main__.FlaskApp object at 0x000001E4382EFD40>
    └ <__main__.FlaskApp object at 0x000001E4382EFD40>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 55, in __setupDB
    self.db = Database(host=configDict['db_hostname'], user=configDict['db_username'], password=configDict['db_password'], database=configDict['db_schema'],
    │         │             │                               │                                   │                                   └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         │             │                               │                                   └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         │             │                               └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         │             └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         └ <class 'backend.db.Database.Database'>
    └ <__main__.FlaskApp object at 0x000001E4382EFD40>

KeyError: 'db_hostname'
2025-04-01 18:19:49.958 | INFO     | __main__:__init__:40 - Starting up...
2025-04-01 18:19:49.959 | INFO     | __main__:create_app:60 - Creating Server...
2025-04-01 18:19:54.069 | ERROR    | __main__:<module>:86 - An error has been caught in function '<module>', process 'MainProcess' (11368), thread 'MainThread' (36928):
Traceback (most recent call last):

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\connection_cext.py", line 365, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
    │    │       │         └ {'host': 'localhost', 'user': 'root', 'password': '', 'password1': '', 'password2': '', 'password3': '', 'database': 'local_m...
    │    │       └ <method 'connect' of '_mysql_connector.MySQL' objects>
    │    └ <_mysql_connector.MySQL object at 0x000001B2CCEDE810>
    └ <mysql.connector.connection_cext.CMySQLConnection object at 0x000001B2CDC8CAD0>

_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'localhost:3306' (10061)


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

> File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 86, in <module>
    fa.create_app()
    │  └ <function FlaskApp.create_app at 0x000001B2CDC79800>
    └ <__main__.FlaskApp object at 0x000001B2CDC5FBC0>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 62, in create_app
    self.__setupDB(self.app)
    │              │    └ <Flask 'main'>
    │              └ <__main__.FlaskApp object at 0x000001B2CDC5FBC0>
    └ <__main__.FlaskApp object at 0x000001B2CDC5FBC0>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 55, in __setupDB
    self.db = Database(host=configDict['dbhost'], user=configDict['dbuser'], password=configDict['dbpw'], database=configDict['dbschema'],
    │         │             │                          │                              │                            └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         │             │                          │                              └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         │             │                          └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         │             └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         └ <class 'backend.db.Database.Database'>
    └ <__main__.FlaskApp object at 0x000001B2CDC5FBC0>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\backend\db\Database.py", line 26, in __init__
    self.pool = self.create_pool(pool_name=pool_name, pool_size=pool_size)
    │           │    │                     │                    └ 15
    │           │    │                     └ 'mypool'
    │           │    └ <function Database.create_pool at 0x000001B2CD77F060>
    │           └ <backend.db.Database.Database object at 0x000001B2CDC5EF00>
    └ <backend.db.Database.Database object at 0x000001B2CDC5EF00>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\backend\db\Database.py", line 37, in create_pool
    pool = mysql.connector.pooling.MySQLConnectionPool(
           │     │         │       └ <class 'mysql.connector.pooling.MySQLConnectionPool'>
           │     │         └ <module 'mysql.connector.pooling' from 'C:\\Users\\chris\\OneDrive\\Desktop\\Masterarbeit neu\\project\\.venv\\Lib\\site-pack...
           │     └ <module 'mysql.connector' from 'C:\\Users\\chris\\OneDrive\\Desktop\\Masterarbeit neu\\project\\.venv\\Lib\\site-packages\\my...
           └ <module 'mysql' from 'C:\\Users\\chris\\OneDrive\\Desktop\\Masterarbeit neu\\project\\.venv\\Lib\\site-packages\\mysql\\__ini...

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\pooling.py", line 490, in __init__
    self.add_connection()
    │    └ <function MySQLConnectionPool.add_connection at 0x000001B2CDC67B00>
    └ <mysql.connector.pooling.MySQLConnectionPool object at 0x000001B2CD8987D0>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\pooling.py", line 613, in add_connection
    cnx = connect(**self._cnx_config)  # type: ignore[assignment]
          │         │    └ {'host': ' localhost', 'port': '3306', 'user': ' root', 'password': '', 'database': ' local_master_project'}
          │         └ <mysql.connector.pooling.MySQLConnectionPool object at 0x000001B2CD8987D0>
          └ <function connect at 0x000001B2CDC65120>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
           │                 │       └ {'host': ' localhost', 'port': '3306', 'user': ' root', 'password': '', 'database': ' local_master_project'}
           │                 └ ()
           └ <class 'mysql.connector.connection_cext.CMySQLConnection'>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\connection_cext.py", line 153, in __init__
    self.connect(**kwargs)
    │    │         └ {'host': ' localhost', 'port': '3306', 'user': ' root', 'password': '', 'database': ' local_master_project'}
    │    └ <function MySQLConnectionAbstract.connect at 0x000001B2CD884FE0>
    └ <mysql.connector.connection_cext.CMySQLConnection object at 0x000001B2CDC8CAD0>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\abstracts.py", line 1529, in connect
    self._open_connection()
    │    └ <function CMySQLConnection._open_connection at 0x000001B2CDC3DBC0>
    └ <mysql.connector.connection_cext.CMySQLConnection object at 0x000001B2CDC8CAD0>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\connection_cext.py", line 370, in _open_connection
    raise get_mysql_exception(
          └ <function get_mysql_exception at 0x000001B2CD7D36A0>

mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)
2025-04-01 18:20:01.492 | INFO     | __main__:__init__:40 - Starting up...
2025-04-01 18:20:01.492 | INFO     | __main__:create_app:60 - Creating Server...
2025-04-01 18:20:05.607 | ERROR    | __main__:<module>:86 - An error has been caught in function '<module>', process 'MainProcess' (9500), thread 'MainThread' (36016):
Traceback (most recent call last):

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\connection_cext.py", line 365, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
    │    │       │         └ {'host': 'localhost', 'user': 'root', 'password': '', 'password1': '', 'password2': '', 'password3': '', 'database': 'local_m...
    │    │       └ <method 'connect' of '_mysql_connector.MySQL' objects>
    │    └ <_mysql_connector.MySQL object at 0x000001E1A685ED40>
    └ <mysql.connector.connection_cext.CMySQLConnection object at 0x000001E1A761CFB0>

_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'localhost:3306' (10061)


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

> File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 86, in <module>
    fa.create_app()
    │  └ <function FlaskApp.create_app at 0x000001E1A7609800>
    └ <__main__.FlaskApp object at 0x000001E1A64AB6E0>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 62, in create_app
    self.__setupDB(self.app)
    │              │    └ <Flask 'main'>
    │              └ <__main__.FlaskApp object at 0x000001E1A64AB6E0>
    └ <__main__.FlaskApp object at 0x000001E1A64AB6E0>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 55, in __setupDB
    self.db = Database(host=configDict['dbhost'], user=configDict['dbuser'], password=configDict['dbpw'], database=configDict['dbschema'],
    │         │             │                          │                              │                            └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         │             │                          │                              └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         │             │                          └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         │             └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         └ <class 'backend.db.Database.Database'>
    └ <__main__.FlaskApp object at 0x000001E1A64AB6E0>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\backend\db\Database.py", line 26, in __init__
    self.pool = self.create_pool(pool_name=pool_name, pool_size=pool_size)
    │           │    │                     │                    └ 15
    │           │    │                     └ 'mypool'
    │           │    └ <function Database.create_pool at 0x000001E1A710F060>
    │           └ <backend.db.Database.Database object at 0x000001E1A446B440>
    └ <backend.db.Database.Database object at 0x000001E1A446B440>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\backend\db\Database.py", line 37, in create_pool
    pool = mysql.connector.pooling.MySQLConnectionPool(
           │     │         │       └ <class 'mysql.connector.pooling.MySQLConnectionPool'>
           │     │         └ <module 'mysql.connector.pooling' from 'C:\\Users\\chris\\OneDrive\\Desktop\\Masterarbeit neu\\project\\.venv\\Lib\\site-pack...
           │     └ <module 'mysql.connector' from 'C:\\Users\\chris\\OneDrive\\Desktop\\Masterarbeit neu\\project\\.venv\\Lib\\site-packages\\my...
           └ <module 'mysql' from 'C:\\Users\\chris\\OneDrive\\Desktop\\Masterarbeit neu\\project\\.venv\\Lib\\site-packages\\mysql\\__ini...

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\pooling.py", line 490, in __init__
    self.add_connection()
    │    └ <function MySQLConnectionPool.add_connection at 0x000001E1A75F7B00>
    └ <mysql.connector.pooling.MySQLConnectionPool object at 0x000001E1A6710B00>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\pooling.py", line 613, in add_connection
    cnx = connect(**self._cnx_config)  # type: ignore[assignment]
          │         │    └ {'host': ' localhost', 'port': '3306', 'user': ' root', 'password': '', 'database': ' local_master_project'}
          │         └ <mysql.connector.pooling.MySQLConnectionPool object at 0x000001E1A6710B00>
          └ <function connect at 0x000001E1A75F5120>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
           │                 │       └ {'host': ' localhost', 'port': '3306', 'user': ' root', 'password': '', 'database': ' local_master_project'}
           │                 └ ()
           └ <class 'mysql.connector.connection_cext.CMySQLConnection'>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\connection_cext.py", line 153, in __init__
    self.connect(**kwargs)
    │    │         └ {'host': ' localhost', 'port': '3306', 'user': ' root', 'password': '', 'database': ' local_master_project'}
    │    └ <function MySQLConnectionAbstract.connect at 0x000001E1A7214FE0>
    └ <mysql.connector.connection_cext.CMySQLConnection object at 0x000001E1A761CFB0>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\abstracts.py", line 1529, in connect
    self._open_connection()
    │    └ <function CMySQLConnection._open_connection at 0x000001E1A75CDBC0>
    └ <mysql.connector.connection_cext.CMySQLConnection object at 0x000001E1A761CFB0>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\connection_cext.py", line 370, in _open_connection
    raise get_mysql_exception(
          └ <function get_mysql_exception at 0x000001E1A71636A0>

mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)
2025-04-01 18:21:37.492 | INFO     | __main__:__init__:40 - Starting up...
2025-04-01 18:21:37.493 | INFO     | __main__:create_app:60 - Creating Server...
2025-04-01 18:21:41.621 | ERROR    | __main__:<module>:86 - An error has been caught in function '<module>', process 'MainProcess' (36432), thread 'MainThread' (28028):
Traceback (most recent call last):

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\connection_cext.py", line 365, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
    │    │       │         └ {'host': 'localhost', 'user': 'root', 'password': '', 'password1': '', 'password2': '', 'password3': '', 'database': 'local_m...
    │    │       └ <method 'connect' of '_mysql_connector.MySQL' objects>
    │    └ <_mysql_connector.MySQL object at 0x000001E34FA497C0>
    └ <mysql.connector.connection_cext.CMySQLConnection object at 0x000001E350F9CFB0>

_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'localhost:3306' (10061)


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

> File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 86, in <module>
    fa.create_app()
    │  └ <function FlaskApp.create_app at 0x000001E350F89800>
    └ <__main__.FlaskApp object at 0x000001E34FE2B6E0>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 62, in create_app
    self.__setupDB(self.app)
    │              │    └ <Flask 'main'>
    │              └ <__main__.FlaskApp object at 0x000001E34FE2B6E0>
    └ <__main__.FlaskApp object at 0x000001E34FE2B6E0>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\main.py", line 55, in __setupDB
    self.db = Database(host=configDict['dbhost'], user=configDict['dbuser'], password=configDict['dbpw'], database=configDict['dbschema'],
    │         │             │                          │                              │                            └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         │             │                          │                              └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         │             │                          └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         │             └ {'dbhost': ' localhost', 'dbschema': ' local_master_project', 'dbuser': ' root', 'dbpw': '', 'main_language': ' en_EN'}
    │         └ <class 'backend.db.Database.Database'>
    └ <__main__.FlaskApp object at 0x000001E34FE2B6E0>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\backend\db\Database.py", line 26, in __init__
    self.pool = self.create_pool(pool_name=pool_name, pool_size=pool_size)
    │           │    │                     │                    └ 15
    │           │    │                     └ 'mypool'
    │           │    └ <function Database.create_pool at 0x000001E350A8F060>
    │           └ <backend.db.Database.Database object at 0x000001E34DE5B440>
    └ <backend.db.Database.Database object at 0x000001E34DE5B440>

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\backend\db\Database.py", line 37, in create_pool
    pool = mysql.connector.pooling.MySQLConnectionPool(
           │     │         │       └ <class 'mysql.connector.pooling.MySQLConnectionPool'>
           │     │         └ <module 'mysql.connector.pooling' from 'C:\\Users\\chris\\OneDrive\\Desktop\\Masterarbeit neu\\project\\.venv\\Lib\\site-pack...
           │     └ <module 'mysql.connector' from 'C:\\Users\\chris\\OneDrive\\Desktop\\Masterarbeit neu\\project\\.venv\\Lib\\site-packages\\my...
           └ <module 'mysql' from 'C:\\Users\\chris\\OneDrive\\Desktop\\Masterarbeit neu\\project\\.venv\\Lib\\site-packages\\mysql\\__ini...

  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\pooling.py", line 490, in __init__
    self.add_connection()
    │    └ <function MySQLConnectionPool.add_connection at 0x000001E350F77B00>
    └ <mysql.connector.pooling.MySQLConnectionPool object at 0x000001E350090B00>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\pooling.py", line 613, in add_connection
    cnx = connect(**self._cnx_config)  # type: ignore[assignment]
          │         │    └ {'host': ' localhost', 'port': '3306', 'user': ' root', 'password': '', 'database': ' local_master_project'}
          │         └ <mysql.connector.pooling.MySQLConnectionPool object at 0x000001E350090B00>
          └ <function connect at 0x000001E350F75120>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
           │                 │       └ {'host': ' localhost', 'port': '3306', 'user': ' root', 'password': '', 'database': ' local_master_project'}
           │                 └ ()
           └ <class 'mysql.connector.connection_cext.CMySQLConnection'>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\connection_cext.py", line 153, in __init__
    self.connect(**kwargs)
    │    │         └ {'host': ' localhost', 'port': '3306', 'user': ' root', 'password': '', 'database': ' local_master_project'}
    │    └ <function MySQLConnectionAbstract.connect at 0x000001E350B94FE0>
    └ <mysql.connector.connection_cext.CMySQLConnection object at 0x000001E350F9CFB0>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\abstracts.py", line 1529, in connect
    self._open_connection()
    │    └ <function CMySQLConnection._open_connection at 0x000001E350F4DBC0>
    └ <mysql.connector.connection_cext.CMySQLConnection object at 0x000001E350F9CFB0>
  File "C:\Users\chris\OneDrive\Desktop\Masterarbeit neu\project\.venv\Lib\site-packages\mysql\connector\connection_cext.py", line 370, in _open_connection
    raise get_mysql_exception(
          └ <function get_mysql_exception at 0x000001E350AE36A0>

mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)
2025-04-01 18:28:26.616 | INFO     | __main__:__init__:44 - Starting up...
2025-04-01 18:28:26.616 | INFO     | __main__:create_app:64 - Creating Server...
2025-04-01 18:28:57.324 | INFO     | backend.util.Toolbox:logToDatabase:42 - 127.0.0.1 /
2025-04-01 18:28:57.659 | INFO     | backend.util.Toolbox:logToDatabase:42 - 127.0.0.1 /css/bootstrap.min.css
2025-04-01 18:28:57.957 | INFO     | backend.util.Toolbox:logToDatabase:42 - 127.0.0.1 /favicon.ico
2025-04-01 18:29:04.699 | INFO     | backend.util.Toolbox:logToDatabase:42 - 127.0.0.1 /index_user
2025-04-01 18:31:32.336 | INFO     | __main__:__init__:44 - Starting up...
2025-04-01 18:31:32.336 | INFO     | __main__:create_app:64 - Creating Server...
2025-04-01 18:31:38.549 | INFO     | backend.util.Toolbox:logToDatabase:42 - 127.0.0.1 /index_user
2025-04-01 18:31:40.197 | INFO     | backend.util.Toolbox:logToDatabase:42 - 127.0.0.1 /index_user
2025-04-01 18:33:37.999 | INFO     | __main__:__init__:44 - Starting up...
2025-04-01 18:33:38.006 | INFO     | __main__:create_app:64 - Creating Server...
2025-04-01 18:33:40.625 | INFO     | backend.util.Toolbox:logToDatabase:42 - 127.0.0.1 /index_user
2025-04-01 18:34:31.885 | INFO     | __main__:__init__:44 - Starting up...
2025-04-01 18:34:31.886 | INFO     | __main__:create_app:64 - Creating Server...
2025-04-01 18:34:34.644 | INFO     | backend.util.Toolbox:logToDatabase:42 - 127.0.0.1 /index_user
2025-04-01 18:34:51.023 | INFO     | __main__:__init__:44 - Starting up...
2025-04-01 18:34:51.030 | INFO     | __main__:create_app:64 - Creating Server...
2025-04-01 18:34:55.347 | INFO     | backend.util.Toolbox:logToDatabase:42 - 127.0.0.1 /index_user
2025-04-01 19:01:27.657 | INFO     | __main__:__init__:45 - Starting up...
2025-04-01 19:01:27.664 | INFO     | __main__:create_app:65 - Creating Server...
2025-04-01 19:01:30.442 | INFO     | backend.util.Toolbox:logToDatabase:42 - 127.0.0.1 /index_user
2025-04-01 19:02:29.734 | INFO     | __main__:__init__:45 - Starting up...
2025-04-01 19:02:29.740 | INFO     | __main__:create_app:65 - Creating Server...
2025-04-01 19:02:32.605 | INFO     | backend.util.Toolbox:logToDatabase:42 - 127.0.0.1 /index_user
2025-04-01 19:04:08.207 | INFO     | __main__:__init__:45 - Starting up...
2025-04-01 19:04:08.207 | INFO     | __main__:create_app:65 - Creating Server...
2025-04-01 19:04:12.343 | INFO     | __main__:__init__:45 - Starting up...
2025-04-01 19:04:12.351 | INFO     | __main__:create_app:65 - Creating Server...
2025-04-01 19:04:14.947 | INFO     | backend.util.Toolbox:logToDatabase:42 - 127.0.0.1 /index_user
2025-04-01 19:13:14.408 | INFO     | __main__:__init__:45 - Starting up...
2025-04-01 19:13:14.414 | INFO     | __main__:create_app:65 - Creating Server...
2025-04-01 19:13:19.295 | INFO     | backend.util.Toolbox:logToDatabase:42 - 127.0.0.1 /index_user
2025-04-01 19:14:23.055 | INFO     | __main__:__init__:45 - Starting up...
2025-04-01 19:14:23.062 | INFO     | __main__:create_app:65 - Creating Server...
2025-04-01 19:14:27.873 | INFO     | backend.util.Toolbox:logToDatabase:42 - 127.0.0.1 /index_user
2025-04-01 19:24:01.681 | INFO     | __main__:__init__:45 - Starting up...
2025-04-01 19:24:01.682 | INFO     | __main__:create_app:65 - Creating Server...
2025-04-01 19:24:06.633 | INFO     | backend.util.Toolbox:logToDatabase:42 - 127.0.0.1 /index_user
